version: 2

project_name: fm

builds:
  - main: .
    binary: fm
    ldflags:
      - -s -w
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: checksums.txt
  algorithm: sha256

changelog:
  sort: asc
